//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alejandria.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Caja
    {
        public System.Guid Id { get; set; }
        public int SucursalId { get; set; }
        public Nullable<System.Guid> OperadorId { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<System.DateTime> FCierre { get; set; }
        public Nullable<float> Inicio { get; set; }
        public Nullable<float> Ingresos { get; set; }
        public Nullable<float> Egresos { get; set; }
        public Nullable<float> Saldo { get; set; }
        public Nullable<float> Cheques { get; set; }
        public Nullable<float> Bonos { get; set; }
        public string PcAlta { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<System.Guid> OperadorAltaId { get; set; }
        public Nullable<int> SucursalAltaId { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<System.Guid> OperadorModificacionId { get; set; }
        public Nullable<int> SucursalModificacionId { get; set; }
    
        public virtual Operador Operador { get; set; }
        public virtual Operador OperadorAlta { get; set; }
        public virtual Operador OperadorModificacion { get; set; }
        public virtual Sucursal Sucursal { get; set; }
        public virtual Sucursal SucursalAlta { get; set; }
        public virtual Sucursal SucursalModificacion { get; set; }
    }
}
