//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alejandria.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CajasMovimiento
    {
        public System.Guid Id { get; set; }
        public System.Guid CajaId { get; set; }
        public Nullable<int> TipoMovimientoCajaId { get; set; }
        public Nullable<int> TipoComprobante { get; set; }
        public Nullable<System.Guid> ComprobanteId { get; set; }
        public Nullable<decimal> Senia { get; set; }
        public Nullable<decimal> Recargo { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public Nullable<decimal> ImpFac { get; set; }
        public Nullable<decimal> Efectivo { get; set; }
        public Nullable<decimal> Tarjeta { get; set; }
        public Nullable<decimal> Cheque { get; set; }
        public Nullable<decimal> Bono { get; set; }
        public string fpcBono { get; set; }
        public Nullable<decimal> Deposito { get; set; }
        public string CajaIdAnt { get; set; }
        public string CompIdAnt { get; set; }
        public string CompLcnAnt { get; set; }
        public Nullable<int> FacturaReservadas { get; set; }
        public string PcAlta { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<System.Guid> OperadorAltaId { get; set; }
        public Nullable<int> SucursalAltaId { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<System.Guid> OperadorModificacionId { get; set; }
        public Nullable<int> SucursalModificacionId { get; set; }
        public Nullable<decimal> Transferencia { get; set; }
    
        public virtual Sucursal Sucursale { get; set; }
        public virtual Sucursal Sucursale1 { get; set; }
        public virtual TiposComprobante TiposComprobante { get; set; }
        public virtual TiposMovimientosCaja TiposMovimientosCaja { get; set; }
        public virtual Operador Operadore { get; set; }
        public virtual Operador Operadore1 { get; set; }
    }
}
