//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alejandria.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.ClientesCuentasCorrientes = new HashSet<ClientesCuentasCorriente>();
            this.Ventas = new HashSet<Venta>();
            this.ClientesMovimientoes = new HashSet<ClientesMovimiento>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<int> SucursalId { get; set; }
        public Nullable<int> Cuenta { get; set; }
        public string Denominacion { get; set; }
        public string Domicilio { get; set; }
        public string DomicilioDoc { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public string Fax { get; set; }
        public string Cuit { get; set; }
        public string Mail { get; set; }
        public Nullable<int> VendedorId { get; set; }
        public Nullable<int> ProvinciaId { get; set; }
        public Nullable<int> LocalidadId { get; set; }
        public Nullable<Alejandria.Entities.Enums.CondicionVentaEnum> CondicionVentaId { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public Nullable<bool> PagoLocal { get; set; }
        public Nullable<int> ZonaId { get; set; }
        public Nullable<int> TipoDocumentoId { get; set; }
        public Nullable<int> CondicionIvaId { get; set; }
        public string Contacto { get; set; }
        public Nullable<int> ProfesionId { get; set; }
        public Nullable<int> EspecialidadId { get; set; }
        public Nullable<Alejandria.Entities.Enums.EstadoCliente> EstadoClienteId { get; set; }
        public Nullable<bool> AceptaConsig { get; set; }
        public string Imagen { get; set; }
        public string Comentarios { get; set; }
        public Nullable<bool> Temp { get; set; }
        public Nullable<float> Recargo { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<System.Guid> OperadorAltaId { get; set; }
        public Nullable<int> SucursalAltaId { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<System.Guid> OperadorModificacionId { get; set; }
        public Nullable<int> SucursalModificacionId { get; set; }
        public Nullable<bool> MandarMail { get; set; }
        public Nullable<bool> Llamar { get; set; }
    
        public virtual CondicionesIVA CondicionesIVA { get; set; }
        public virtual CondicionesVenta CondicionesVenta { get; set; }
        public virtual Especialidad Especialidad { get; set; }
        public virtual EstadosCliente EstadosCliente { get; set; }
        public virtual Localidad Localidad { get; set; }
        public virtual Profesion Profesione { get; set; }
        public virtual Provincia Provincia { get; set; }
        public virtual Sucursal Sucursal { get; set; }
        public virtual Sucursal SucursalAlta { get; set; }
        public virtual Sucursal SucursalModificacion { get; set; }
        public virtual TiposDocumentosIdentidad TiposDocumentosIdentidad { get; set; }
        public virtual Zona Zona { get; set; }
        public virtual ICollection<ClientesCuentasCorriente> ClientesCuentasCorrientes { get; set; }
        public virtual ICollection<Venta> Ventas { get; set; }
        public virtual ICollection<ClientesMovimiento> ClientesMovimientoes { get; set; }
        public virtual Vendedor Vendedore { get; set; }
        public virtual Operador Operadore { get; set; }
        public virtual Operador Operadore1 { get; set; }
    }
}
