//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alejandria.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public Venta()
        {
            this.ClientesCuentasCorrientes = new HashSet<ClientesCuentasCorriente>();
        }
    
        public System.Guid Id { get; set; }
        public string LCN { get; set; }
        public int ComprobanteId { get; set; }
        public System.Guid ClienteId { get; set; }
        public string LetraComprobante { get; set; }
        public int PuntoVenta { get; set; }
        public int NumeroComprobante { get; set; }
        public Nullable<System.DateTime> FechaComprobante { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public Nullable<Alejandria.Entities.Enums.CondicionVentaEnum> CondicionVentaId { get; set; }
        public string Concepto { get; set; }
        public decimal ImporteNeto { get; set; }
        public decimal ImporteIva { get; set; }
        public Nullable<decimal> ImporteSena { get; set; }
        public Nullable<System.DateTime> FechaUltimoPago { get; set; }
        public Nullable<decimal> TotalPagado { get; set; }
        public int EstadoVentaId { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public int SucursalAltaId { get; set; }
        public System.Guid OperadorAltaId { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> SucursalModificacionId { get; set; }
        public Nullable<System.Guid> OperadorModificacionId { get; set; }
        public Nullable<System.Guid> OperadorAutoriza { get; set; }
        public string ValidacionUsuario { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual ICollection<ClientesCuentasCorriente> ClientesCuentasCorrientes { get; set; }
        public virtual CondicionesVenta CondicionesVenta { get; set; }
        public virtual EstadosVenta EstadosVenta { get; set; }
        public virtual Operador Operadore { get; set; }
        public virtual Operador Operadore1 { get; set; }
        public virtual Operador Operadore2 { get; set; }
        public virtual Sucursal Sucursale { get; set; }
        public virtual Sucursal Sucursale1 { get; set; }
        public virtual TiposComprobante TiposComprobante { get; set; }
    }
}
