//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alejandria.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Alejandria.Entities;
    
    public partial class AlejandriaDbContext : DbContext
    {
        public AlejandriaDbContext()
            : base("name=AlejandriaDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CategoriaOperador> CategoriaOperadors { get; set; }
        public virtual DbSet<CondicionesIVA> CondicionesIVAs { get; set; }
        public virtual DbSet<CondicionesVenta> CondicionesVentas { get; set; }
        public virtual DbSet<Especialidad> Especialidads { get; set; }
        public virtual DbSet<EstadosCliente> EstadosClientes { get; set; }
        public virtual DbSet<Localidad> Localidads { get; set; }
        public virtual DbSet<Operador> Operadors { get; set; }
        public virtual DbSet<Personal> Personals { get; set; }
        public virtual DbSet<Profesion> Profesions { get; set; }
        public virtual DbSet<Provincia> Provincias { get; set; }
        public virtual DbSet<Sucursal> Sucursals { get; set; }
        public virtual DbSet<TiposDocumentosIdentidad> TiposDocumentosIdentidads { get; set; }
        public virtual DbSet<Zona> Zonas { get; set; }
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<Vendedor> Vendedors { get; set; }
    }
}
