//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alejandria.Win.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alejandria.Win.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _04 {
            get {
                object obj = ResourceManager.GetObject("04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Add_New_blue {
            get {
                object obj = ResourceManager.GetObject("Add_New_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Bank {
            get {
                object obj = ResourceManager.GetObject("Bank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Book_Open {
            get {
                object obj = ResourceManager.GetObject("Book-Open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Bullets {
            get {
                object obj = ResourceManager.GetObject("Bullets", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cash {
            get {
                object obj = ResourceManager.GetObject("Cash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cheque_01 {
            get {
                object obj = ResourceManager.GetObject("Cheque-01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cobradores {
            get {
                object obj = ResourceManager.GetObject("cobradores", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECCIONE LOCALIDAD.
        /// </summary>
        internal static string ComboBoxOptionSeleccinarLocalidad {
            get {
                return ResourceManager.GetString("ComboBoxOptionSeleccinarLocalidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECCIONE CONDICION.
        /// </summary>
        internal static string ComboBoxOptionSeleccionarCondicionCompra {
            get {
                return ResourceManager.GetString("ComboBoxOptionSeleccionarCondicionCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECCIONE FORMA DE PAGO.
        /// </summary>
        internal static string ComboBoxOptionSeleccionarFormaPago {
            get {
                return ResourceManager.GetString("ComboBoxOptionSeleccionarFormaPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECCIONE PROVINCIA.
        /// </summary>
        internal static string ComboBoxOptionSeleccionarProvincia {
            get {
                return ResourceManager.GetString("ComboBoxOptionSeleccionarProvincia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Esta seguro que desea eliminar el libro?.
        /// </summary>
        internal static string ConfirmationMessageEliminarLibro {
            get {
                return ResourceManager.GetString("ConfirmationMessageEliminarLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ConsignacionCliente {
            get {
                object obj = ResourceManager.GetObject("ConsignacionCliente", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Counting_Machine {
            get {
                object obj = ResourceManager.GetObject("Counting-Machine", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Customer {
            get {
                object obj = ResourceManager.GetObject("Customer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Customer1 {
            get {
                object obj = ResourceManager.GetObject("Customer1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CustomerAlejandria {
            get {
                object obj = ResourceManager.GetObject("CustomerAlejandria", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Data_Edit {
            get {
                object obj = ResourceManager.GetObject("Data_Edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Data_Edit_Con {
            get {
                object obj = ResourceManager.GetObject("Data-Edit-Con", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Data_Edit_Con1 {
            get {
                object obj = ResourceManager.GetObject("Data-Edit-Con1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Data_Files {
            get {
                object obj = ResourceManager.GetObject("Data-Files", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap devlights {
            get {
                object obj = ResourceManager.GetObject("devlights", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap devoluviones {
            get {
                object obj = ResourceManager.GetObject("devoluviones", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap devolver {
            get {
                object obj = ResourceManager.GetObject("devolver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Libro.
        /// </summary>
        internal static string DialogTitleEliminarLibro {
            get {
                return ResourceManager.GetString("DialogTitleEliminarLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap error {
            get {
                object obj = ResourceManager.GetObject("error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontro detalle de la consignación.
        /// </summary>
        internal static string ErrorBuscarConsignacionVacio {
            get {
                return ResourceManager.GetString("ErrorBuscarConsignacionVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ErrorIcon {
            get {
                object obj = ResourceManager.GetObject("ErrorIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El banco no puede eliminarse ya que tiene cheques de terceros o movimientos de tarjeta asociados.
        /// </summary>
        internal static string ErrorMessageBancoConDatos {
            get {
                return ResourceManager.GetString("ErrorMessageBancoConDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El cliente que esta tratando de eliminar tiene deudas activas. Por favor revíselas he intente nuevamente.
        /// </summary>
        internal static string ErrorMessageClienteConDeuda {
            get {
                return ResourceManager.GetString("ErrorMessageClienteConDeuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede eliminar el cliente tiene ventas asociadas.
        /// </summary>
        internal static string ErrorMessageClienteConVentas {
            get {
                return ResourceManager.GetString("ErrorMessageClienteConVentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las cantidades vendidas y devueltas no pueden ser mayor a la cantidad consignada.
        /// </summary>
        internal static string ErrorMessageDifferentCuantity {
            get {
                return ResourceManager.GetString("ErrorMessageDifferentCuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede eliminar la editorial tiene titulos asociados.
        /// </summary>
        internal static string ErrorMessageEditorialConTitulos {
            get {
                return ResourceManager.GetString("ErrorMessageEditorialConTitulos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las claves ingresadas con son las mismas.
        /// </summary>
        internal static string ErrorMessagePasswordsDiferentes {
            get {
                return ResourceManager.GetString("ErrorMessagePasswordsDiferentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tiene los permisos para realizar esta operación.
        /// </summary>
        internal static string ErrorMessageRolesRequeridos {
            get {
                return ResourceManager.GetString("ErrorMessageRolesRequeridos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar un cliente.
        /// </summary>
        internal static string ErrorMessageSeleccionarCliente {
            get {
                return ResourceManager.GetString("ErrorMessageSeleccionarCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede eliminar la sub temas tiene titulos asociados.
        /// </summary>
        internal static string ErrorMessageSubTemasConTitulos {
            get {
                return ResourceManager.GetString("ErrorMessageSubTemasConTitulos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe agregar al menos un libro a la venta.
        /// </summary>
        internal static string ErrorMessageVentaSinLibros {
            get {
                return ResourceManager.GetString("ErrorMessageVentaSinLibros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Garbage_Closed {
            get {
                object obj = ResourceManager.GetObject("Garbage_Closed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se detecto una caja anterior abierta. La misma se cerró y se abrió una nueva para el usuario.
        /// </summary>
        internal static string InfoMessageCajaAnteriorCerradaAutomaticamente {
            get {
                return ResourceManager.GetString("InfoMessageCajaAnteriorCerradaAutomaticamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir Caja.
        /// </summary>
        internal static string LabelAbrirCaja {
            get {
                return ResourceManager.GetString("LabelAbrirCaja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anular Seña.
        /// </summary>
        internal static string LabelAnularSenia {
            get {
                return ResourceManager.GetString("LabelAnularSenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autores.
        /// </summary>
        internal static string LabelAutores {
            get {
                return ResourceManager.GetString("LabelAutores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bancos.
        /// </summary>
        internal static string LabelBancos {
            get {
                return ResourceManager.GetString("LabelBancos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerra Caja.
        /// </summary>
        internal static string LabelCerrarCaja {
            get {
                return ResourceManager.GetString("LabelCerrarCaja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientes.
        /// </summary>
        internal static string LabelClientes {
            get {
                return ResourceManager.GetString("LabelClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compras.
        /// </summary>
        internal static string LabelCompras {
            get {
                return ResourceManager.GetString("LabelCompras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Esta seguro que abrir la caja para el usuario actual: {0}?.
        /// </summary>
        internal static string LabelConfirmarAbrirCaja {
            get {
                return ResourceManager.GetString("LabelConfirmarAbrirCaja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Esta seguro que cerrar la caja para el usuario actual: {0}?.
        /// </summary>
        internal static string LabelConfirmarCerrarCaja {
            get {
                return ResourceManager.GetString("LabelConfirmarCerrarCaja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Autor.
        /// </summary>
        internal static string LabelCrearAutor {
            get {
                return ResourceManager.GetString("LabelCrearAutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Banco.
        /// </summary>
        internal static string LabelCrearBanco {
            get {
                return ResourceManager.GetString("LabelCrearBanco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Cliente.
        /// </summary>
        internal static string LabelCrearCliente {
            get {
                return ResourceManager.GetString("LabelCrearCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Cobrador.
        /// </summary>
        internal static string LabelCrearCobrador {
            get {
                return ResourceManager.GetString("LabelCrearCobrador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Cuenta.
        /// </summary>
        internal static string LabelCrearCuenta {
            get {
                return ResourceManager.GetString("LabelCrearCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Editorial.
        /// </summary>
        internal static string LabelCrearEditorial {
            get {
                return ResourceManager.GetString("LabelCrearEditorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Libro.
        /// </summary>
        internal static string LabelCrearLibro {
            get {
                return ResourceManager.GetString("LabelCrearLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Orden de Pago.
        /// </summary>
        internal static string LabelCrearOrdenDePago {
            get {
                return ResourceManager.GetString("LabelCrearOrdenDePago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Pago.
        /// </summary>
        internal static string LabelCrearPago {
            get {
                return ResourceManager.GetString("LabelCrearPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Proveedor.
        /// </summary>
        internal static string LabelCrearProveedor {
            get {
                return ResourceManager.GetString("LabelCrearProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Proveedor Gasto.
        /// </summary>
        internal static string LabelCrearProveedorGasto {
            get {
                return ResourceManager.GetString("LabelCrearProveedorGasto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Sub Tema.
        /// </summary>
        internal static string LabelCrearSubTema {
            get {
                return ResourceManager.GetString("LabelCrearSubTema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Tema.
        /// </summary>
        internal static string LabelCrearTema {
            get {
                return ResourceManager.GetString("LabelCrearTema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Usuario/Operador.
        /// </summary>
        internal static string LabelCrearUsuarioOperador {
            get {
                return ResourceManager.GetString("LabelCrearUsuarioOperador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Vendedor.
        /// </summary>
        internal static string LabelCrearVendedor {
            get {
                return ResourceManager.GetString("LabelCrearVendedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle de Autor.
        /// </summary>
        internal static string LabelDetalleAutor {
            get {
                return ResourceManager.GetString("LabelDetalleAutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle de Banco.
        /// </summary>
        internal static string LabelDetalleBanco {
            get {
                return ResourceManager.GetString("LabelDetalleBanco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle Cliente.
        /// </summary>
        internal static string LabelDetalleCliente {
            get {
                return ResourceManager.GetString("LabelDetalleCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle Cuenta.
        /// </summary>
        internal static string LabelDetalleCuenta {
            get {
                return ResourceManager.GetString("LabelDetalleCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle Editorial.
        /// </summary>
        internal static string LabelDetalleEditorial {
            get {
                return ResourceManager.GetString("LabelDetalleEditorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle Libro.
        /// </summary>
        internal static string LabelDetalleLibro {
            get {
                return ResourceManager.GetString("LabelDetalleLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle Orden de Pago.
        /// </summary>
        internal static string LabelDetalleOrdenDePago {
            get {
                return ResourceManager.GetString("LabelDetalleOrdenDePago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle Pago.
        /// </summary>
        internal static string LabelDetallePago {
            get {
                return ResourceManager.GetString("LabelDetallePago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle Proveedor.
        /// </summary>
        internal static string LabelDetalleProveedor {
            get {
                return ResourceManager.GetString("LabelDetalleProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle Proveedor Gasto.
        /// </summary>
        internal static string LabelDetalleProveedorGasto {
            get {
                return ResourceManager.GetString("LabelDetalleProveedorGasto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle Sub Tema.
        /// </summary>
        internal static string LabelDetalleSubTema {
            get {
                return ResourceManager.GetString("LabelDetalleSubTema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle Tema.
        /// </summary>
        internal static string LabelDetalleTema {
            get {
                return ResourceManager.GetString("LabelDetalleTema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle Usuario.
        /// </summary>
        internal static string LabelDetalleUsuario {
            get {
                return ResourceManager.GetString("LabelDetalleUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Autor.
        /// </summary>
        internal static string LabelEditarAutor {
            get {
                return ResourceManager.GetString("LabelEditarAutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Banco.
        /// </summary>
        internal static string LabelEditarBanco {
            get {
                return ResourceManager.GetString("LabelEditarBanco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Cliente.
        /// </summary>
        internal static string LabelEditarCliente {
            get {
                return ResourceManager.GetString("LabelEditarCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Cobrador.
        /// </summary>
        internal static string LabelEditarCobrador {
            get {
                return ResourceManager.GetString("LabelEditarCobrador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Cuenta.
        /// </summary>
        internal static string LabelEditarCuenta {
            get {
                return ResourceManager.GetString("LabelEditarCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Editorial.
        /// </summary>
        internal static string LabelEditarEditorial {
            get {
                return ResourceManager.GetString("LabelEditarEditorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Libro.
        /// </summary>
        internal static string LabelEditarLibro {
            get {
                return ResourceManager.GetString("LabelEditarLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Usuario/Operador.
        /// </summary>
        internal static string LabelEditarOperador {
            get {
                return ResourceManager.GetString("LabelEditarOperador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Orden de Pago.
        /// </summary>
        internal static string LabelEditarOrdenDePago {
            get {
                return ResourceManager.GetString("LabelEditarOrdenDePago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Pago.
        /// </summary>
        internal static string LabelEditarPago {
            get {
                return ResourceManager.GetString("LabelEditarPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Proveedor.
        /// </summary>
        internal static string LabelEditarProveedor {
            get {
                return ResourceManager.GetString("LabelEditarProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Proveedor Gasto.
        /// </summary>
        internal static string LabelEditarProveedorGasto {
            get {
                return ResourceManager.GetString("LabelEditarProveedorGasto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Sub Tema.
        /// </summary>
        internal static string LabelEditarSubTema {
            get {
                return ResourceManager.GetString("LabelEditarSubTema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Tema.
        /// </summary>
        internal static string LabelEditarTema {
            get {
                return ResourceManager.GetString("LabelEditarTema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Vendedor.
        /// </summary>
        internal static string LabelEditarVendedor {
            get {
                return ResourceManager.GetString("LabelEditarVendedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editoriales.
        /// </summary>
        internal static string LabelEditoriales {
            get {
                return ResourceManager.GetString("LabelEditoriales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Usuario.
        /// </summary>
        internal static string LabelElimimnarUsuario {
            get {
                return ResourceManager.GetString("LabelElimimnarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Autor.
        /// </summary>
        internal static string LabelEliminarAutor {
            get {
                return ResourceManager.GetString("LabelEliminarAutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Banco.
        /// </summary>
        internal static string LabelEliminarBanco {
            get {
                return ResourceManager.GetString("LabelEliminarBanco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Cliente.
        /// </summary>
        internal static string LabelEliminarCliente {
            get {
                return ResourceManager.GetString("LabelEliminarCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar Cuenta.
        /// </summary>
        internal static string LabelEliminarCuenta {
            get {
                return ResourceManager.GetString("LabelEliminarCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Pago.
        /// </summary>
        internal static string LabelEliminarDetalle {
            get {
                return ResourceManager.GetString("LabelEliminarDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Editorial.
        /// </summary>
        internal static string LabelEliminarEditorial {
            get {
                return ResourceManager.GetString("LabelEliminarEditorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Libro.
        /// </summary>
        internal static string LabelEliminarLibro {
            get {
                return ResourceManager.GetString("LabelEliminarLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Orden de Pago.
        /// </summary>
        internal static string LabelEliminarOrdenDePago {
            get {
                return ResourceManager.GetString("LabelEliminarOrdenDePago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Pago.
        /// </summary>
        internal static string LabelEliminarPago {
            get {
                return ResourceManager.GetString("LabelEliminarPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Proveedor.
        /// </summary>
        internal static string LabelEliminarProveedor {
            get {
                return ResourceManager.GetString("LabelEliminarProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Proveedor Gasto.
        /// </summary>
        internal static string LabelEliminarProveedorGasto {
            get {
                return ResourceManager.GetString("LabelEliminarProveedorGasto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Sub Tema.
        /// </summary>
        internal static string LabelEliminarSubTema {
            get {
                return ResourceManager.GetString("LabelEliminarSubTema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Tema.
        /// </summary>
        internal static string LabelEliminarTema {
            get {
                return ResourceManager.GetString("LabelEliminarTema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprimir.
        /// </summary>
        internal static string LabelImprimir {
            get {
                return ResourceManager.GetString("LabelImprimir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presupuesto.
        /// </summary>
        internal static string LabelPresupuesto {
            get {
                return ResourceManager.GetString("LabelPresupuesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Temas.
        /// </summary>
        internal static string LabelSubTemas {
            get {
                return ResourceManager.GetString("LabelSubTemas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ventas.
        /// </summary>
        internal static string LabelVentas {
            get {
                return ResourceManager.GetString("LabelVentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap loading {
            get {
                object obj = ResourceManager.GetObject("loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Login_01 {
            get {
                object obj = ResourceManager.GetObject("Login-01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Login_01_16x16 {
            get {
                object obj = ResourceManager.GetObject("Login-01_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon LogoLaPaz {
            get {
                object obj = ResourceManager.GetObject("LogoLaPaz", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El cliente {0}, DNI:{1} no se encuentra actívo.
        /// </summary>
        internal static string MensajeClienteInactivo {
            get {
                return ResourceManager.GetString("MensajeClienteInactivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Esta seguro que desea anular esta seña?.
        /// </summary>
        internal static string MensajeConfirmarAnularSenia {
            get {
                return ResourceManager.GetString("MensajeConfirmarAnularSenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La devolución se realizó con éxito.
        /// </summary>
        internal static string MessageDevolucionExitosa {
            get {
                return ResourceManager.GetString("MessageDevolucionExitosa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La compra se realizó con éxito.
        /// </summary>
        internal static string MessageSuccessCompraExitosa {
            get {
                return ResourceManager.GetString("MessageSuccessCompraExitosa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La consignación se realizó con éxito.
        /// </summary>
        internal static string MessageSuccessConsignacionExitosa {
            get {
                return ResourceManager.GetString("MessageSuccessConsignacionExitosa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagos guardados con éxito.
        /// </summary>
        internal static string MessageSuccessPagoExitoso {
            get {
                return ResourceManager.GetString("MessageSuccessPagoExitoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La seña se cargó con éxito.
        /// </summary>
        internal static string MessageSuccessSeniaExitosa {
            get {
                return ResourceManager.GetString("MessageSuccessSeniaExitosa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La venta se realizó con éxito.
        /// </summary>
        internal static string MessageSuccessVentaExitosa {
            get {
                return ResourceManager.GetString("MessageSuccessVentaExitosa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las funciones han sido asignadas correctamente.
        /// </summary>
        internal static string MessageSucessAsignarFuncionesARoles {
            get {
                return ResourceManager.GetString("MessageSucessAsignarFuncionesARoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Money_Credit_Card {
            get {
                object obj = ResourceManager.GetObject("Money_Credit_Card", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pagar {
            get {
                object obj = ResourceManager.GetObject("Pagar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pagoCuota {
            get {
                object obj = ResourceManager.GetObject("pagoCuota", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pagoCuotaCobradores {
            get {
                object obj = ResourceManager.GetObject("pagoCuotaCobradores", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Print_16x16 {
            get {
                object obj = ResourceManager.GetObject("Print-16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Printer {
            get {
                object obj = ResourceManager.GetObject("Printer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Purchase_Order {
            get {
                object obj = ResourceManager.GetObject("Purchase-Order", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Reload {
            get {
                object obj = ResourceManager.GetObject("Reload", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Reload_16x16 {
            get {
                object obj = ResourceManager.GetObject("Reload_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RendirConsignacion {
            get {
                object obj = ResourceManager.GetObject("RendirConsignacion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap reporte {
            get {
                object obj = ResourceManager.GetObject("reporte", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap reservada {
            get {
                object obj = ResourceManager.GetObject("reservada", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Sales_Order {
            get {
                object obj = ResourceManager.GetObject("Sales-Order", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap seña {
            get {
                object obj = ResourceManager.GetObject("seña", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap settings {
            get {
                object obj = ResourceManager.GetObject("settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anular Senia.
        /// </summary>
        internal static string TituloConfirmarAnularSenia {
            get {
                return ResourceManager.GetString("TituloConfirmarAnularSenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anulación Completa.
        /// </summary>
        internal static string TooltipAnulacionCompleta {
            get {
                return ResourceManager.GetString("TooltipAnulacionCompleta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anulación Parcial.
        /// </summary>
        internal static string TooltipAnulacionParcial {
            get {
                return ResourceManager.GetString("TooltipAnulacionParcial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap van {
            get {
                object obj = ResourceManager.GetObject("van", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Van___01 {
            get {
                object obj = ResourceManager.GetObject("Van - 01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Van___02 {
            get {
                object obj = ResourceManager.GetObject("Van - 02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap View_Details {
            get {
                object obj = ResourceManager.GetObject("View_Details", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap warning {
            get {
                object obj = ResourceManager.GetObject("warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede seleccionar porque la cantidad seleccionada supera al stock disponible.
        /// </summary>
        internal static string WarningMessageCantidadSeleccionadaSuperaStockDisponible {
            get {
                return ResourceManager.GetString("WarningMessageCantidadSeleccionadaSuperaStockDisponible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pueden pasar libros porque no existe stock.
        /// </summary>
        internal static string WarningMessagePasarStockLibro {
            get {
                return ResourceManager.GetString("WarningMessagePasarStockLibro", resourceCulture);
            }
        }
    }
}
